import Float64 from "float64"
import Json from "json"

let printSomething = () => {
	print("simple object: ")
	print(Json.toStringPretty(Json.JSONObject([("hello", Json.JSONString("world!"))])))

	let test = Json.JSONArray([
		Json.JSONNull,
		Json.JSONBoolean(true),
		Json.JSONBoolean(false),
		Json.JSONNumber(Float64.fromNumber(2)),
		Json.JSONNumber(Float64.fromNumber(-2)),
		Json.JSONNumber(Float64.fromNumber(-0)),
		Json.JSONNumber(Float64.fromNumber(1E200)),
		Json.JSONNumber(Float64.fromNumber(1E-200)),
		// Json.JSONNumber(Float64.fromNumber(inf)),
		Json.JSONString("🤘🏻 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Hello\n\"wo</ \u007F \u0080 rld\"! 🤘🏻"),
		Json.JSONArray([]),
		Json.JSONArray([Json.JSONNull]),
		Json.JSONArray([
			Json.JSONNumber(Float64.fromNumber(1)),
			Json.JSONNumber(Float64.fromNumber(2)),
			Json.JSONNumber(Float64.fromNumber(3))
		]),
		Json.JSONObject([
			("pinco", Json.JSONString("pallino")),
			("pippo", Json.JSONNumber(Float64.fromNumber(4543)))
		]),
		Json.JSONObject([
			("just", Json.JSONString("one"))
		]),
		Json.JSONObject([])
	])

	print("ugly:")
	print(Json.toStringCompact(test))
	print("")
	print("pretty:")
	print(Json.toStringPretty(test))
	print("")
	print("prettier:")
	// Compiler for some reason says the fields of FormattingSettings are not public.
	// See https://github.com/grain-lang/grain/issues/190#issuecomment-851015909
	print(Json.toString(test, {
		indentation: Json.IndentWithTab,
		arrayFormat: Json.OneArrayEntryPerLine,
		objectFormat: Json.OneObjectEntryPerLine,
		lineEnding: Json.LineFeed,
		finishWithNewLine: true,
		escapeAllControlPoints: true,
		escapeHTMLUnsafeSequences: true,
		escapeNonASCII: true
	} : Json.FormattingSettings))

	print("")
	print("toString:")
	print(Json.toStringPretty(test))
	print(Json.toStringPretty(Json.JSONObject([("simple", Json.JSONString("as that!"))])))

	let infinity = Float64.div(Float64.fromNumber(1), Float64.fromNumber(0))
	let nan = Float64.div(Float64.fromNumber(0), Float64.fromNumber(0))
	let negativeinfinity = Float64.div(Float64.fromNumber(-1), Float64.fromNumber(0))

	print("not allowed:")
	print(Json.toStringCompact(Json.JSONArray([Json.JSONNumber(infinity), Json.JSONNumber(negativeinfinity), Json.JSONNumber(nan)])))
}

printSomething();
